### ISSUE TITLE
auto printing

### ISSUE THREAD

**Issue by vinny0015** [nordcomputer/printmailattachment#2]
hello can you help me recode this to run every 5 minutes? to pull new emails?

**Comment by nordcomputer** [comment]
on what system are you? In Linux it should be very simple with a cronjob...

**Comment by vinny0015** [comment]
rpi running rasbarian i set up crone testing now
# @reboot sudo python3 /home/apcinc/Downloads/printmailattachment-master/printm>
# */5 * * * * python3 /home/apcinc/Downloads/printmailattachment-master/printma>

does this look correct?

**Comment by nordcomputer** [comment]
looks correct to me - is it not working?

**Comment by vinny0015** [comment]
no :(

**Comment by nordcomputer** [comment]
hmm...I think, the sudo is wrong there - you need to setup a cronjob for the root user.
Have you tested a simpler script (for example to write into a logfile)?

**Comment by nordcomputer** [comment]
And normally, the script should run without root permissions (I guess).

**Comment by vinny0015** [comment]
no would you mind using team viewer and checking? i can compensate im not good at coding

**Comment by nordcomputer** [comment]
do you have Discord or something?

**Comment by nordcomputer** [comment]
And please, no compensating ;-)

**Comment by vinny0015** [comment]
yes i dont have voice though

**Comment by vinny0015** [comment]
Tomatoes#6868
